name: test

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 
        
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event.inputs.logLevel }} == "warning"
        name: step1         
        run: |
          echo "Log level: ${{ github.event.inputs.logLevel }}"
          echo "Tags: ${{ github.event.inputs.tags }}"
      - if: ${{ github.event.inputs.logLevel }} == "information"
        name: step2        
        run: echo "hello"
